"""
app/generator/templates/pytorch_template.py
Jinja2 template string for PyTorch training script generation.
"""

PYTORCH_TEMPLATE = '''"""
Auto-generated by Paper2Code
Model     : {{ model }}
Dataset   : {{ dataset }}
Task      : {{ task }}
Generated : {{ timestamp }}
"""

import os
import logging
import mlflow
import mlflow.pytorch
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, random_split
from torchvision import datasets, transforms, models

# ── Logging Setup ─────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler("training.log"),
    ],
)
log = logging.getLogger("{{ model }}_trainer")

# ── Hyperparameters ───────────────────────────────────────────
CONFIG = {
    "model":       "{{ model }}",
    "dataset":     "{{ dataset }}",
    "epochs":      {{ epochs }},
    "batch_size":  {{ batch_size }},
    "lr":          {{ lr }},
    "optimizer":   "{{ optimizer }}",
    "loss":        "{{ loss }}",
    "num_classes": {{ num_classes }},
    "device":      "cuda" if torch.cuda.is_available() else "cpu",
    "val_split":   0.2,
    "seed":        42,
}

torch.manual_seed(CONFIG["seed"])
device = torch.device(CONFIG["device"])
log.info(f"Using device: {device}")


# ── Data Loading ──────────────────────────────────────────────
def get_transforms():
    train_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomCrop(224, padding=4),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225]),
    ])
    val_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225]),
    ])
    return train_transform, val_transform


def get_dataloaders():
    train_tf, val_tf = get_transforms()
    log.info(f"Loading dataset: {CONFIG['dataset']}")

    # NOTE: Replace with your actual dataset path/class
    # Example shown uses CIFAR-10 for demonstration
    try:
        full_dataset = datasets.CIFAR10(
            root="./data", train=True, download=True, transform=train_tf
        )
    except Exception as e:
        log.error(f"Dataset loading failed: {e}")
        raise

    val_size  = int(len(full_dataset) * CONFIG["val_split"])
    train_size = len(full_dataset) - val_size
    train_ds, val_ds = random_split(full_dataset, [train_size, val_size])
    val_ds.dataset.transform = val_tf

    train_loader = DataLoader(train_ds, batch_size=CONFIG["batch_size"],
                              shuffle=True,  num_workers=2, pin_memory=True)
    val_loader   = DataLoader(val_ds,   batch_size=CONFIG["batch_size"],
                              shuffle=False, num_workers=2, pin_memory=True)

    log.info(f"Train: {train_size} | Val: {val_size} samples")
    return train_loader, val_loader


# ── Model ─────────────────────────────────────────────────────
def get_model():
    log.info(f"Building model: {CONFIG['model']}")
    try:
        {% if model == "ResNet" %}
        model = models.resnet50(pretrained=True)
        model.fc = nn.Linear(model.fc.in_features, CONFIG["num_classes"])
        {% elif model == "VGG" %}
        model = models.vgg16(pretrained=True)
        model.classifier[6] = nn.Linear(4096, CONFIG["num_classes"])
        {% elif model == "EfficientNet" %}
        model = models.efficientnet_b0(pretrained=True)
        model.classifier[1] = nn.Linear(model.classifier[1].in_features, CONFIG["num_classes"])
        {% elif model == "MobileNet" %}
        model = models.mobilenet_v2(pretrained=True)
        model.classifier[1] = nn.Linear(model.classifier[1].in_features, CONFIG["num_classes"])
        {% elif model == "DenseNet" %}
        model = models.densenet121(pretrained=True)
        model.classifier = nn.Linear(model.classifier.in_features, CONFIG["num_classes"])
        {% else %}
        # Custom model — modify this class for your architecture
        class CustomModel(nn.Module):
            def __init__(self):
                super().__init__()
                self.features = nn.Sequential(
                    nn.Conv2d(3, 64, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
                    nn.Conv2d(64, 128, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
                    nn.Conv2d(128, 256, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
                )
                self.classifier = nn.Sequential(
                    nn.Flatten(),
                    nn.Linear(256 * 28 * 28, 512), nn.ReLU(), nn.Dropout(0.5),
                    nn.Linear(512, CONFIG["num_classes"]),
                )
            def forward(self, x):
                return self.classifier(self.features(x))
        model = CustomModel()
        {% endif %}
    except Exception as e:
        log.error(f"Model creation failed: {e}")
        raise

    return model.to(device)


# ── Loss & Optimizer ──────────────────────────────────────────
def get_criterion():
    losses = {
        "CrossEntropyLoss": nn.CrossEntropyLoss(),
        "MSELoss":          nn.MSELoss(),
        "BCELoss":          nn.BCELoss(),
        "NLLLoss":          nn.NLLLoss(),
    }
    return losses.get(CONFIG["loss"], nn.CrossEntropyLoss())


def get_optimizer(model):
    optimizers = {
        "Adam":    optim.Adam(model.parameters(),  lr=CONFIG["lr"]),
        "SGD":     optim.SGD(model.parameters(),   lr=CONFIG["lr"], momentum=0.9, weight_decay=1e-4),
        "AdamW":   optim.AdamW(model.parameters(), lr=CONFIG["lr"]),
        "RMSProp": optim.RMSprop(model.parameters(), lr=CONFIG["lr"]),
    }
    return optimizers.get(CONFIG["optimizer"], optim.Adam(model.parameters(), lr=CONFIG["lr"]))


# ── Training Loop ─────────────────────────────────────────────
def train_one_epoch(model, loader, criterion, optimizer, epoch):
    model.train()
    total_loss, correct, total = 0.0, 0, 0

    for batch_idx, (inputs, targets) in enumerate(loader):
        try:
            inputs, targets = inputs.to(device), targets.to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()
            _, predicted = outputs.max(1)
            total   += targets.size(0)
            correct += predicted.eq(targets).sum().item()

            if batch_idx % 50 == 0:
                log.debug(f"Epoch {epoch} | Batch {batch_idx}/{len(loader)} | Loss: {loss.item():.4f}")

        except Exception as e:
            log.error(f"Training batch {batch_idx} failed: {e}")
            continue

    avg_loss = total_loss / len(loader)
    accuracy = 100.0 * correct / total
    return avg_loss, accuracy


def validate(model, loader, criterion):
    model.eval()
    total_loss, correct, total = 0.0, 0, 0

    with torch.no_grad():
        for inputs, targets in loader:
            try:
                inputs, targets = inputs.to(device), targets.to(device)
                outputs = model(inputs)
                loss = criterion(outputs, targets)
                total_loss += loss.item()
                _, predicted = outputs.max(1)
                total   += targets.size(0)
                correct += predicted.eq(targets).sum().item()
            except Exception as e:
                log.error(f"Validation batch failed: {e}")
                continue

    avg_loss = total_loss / len(loader)
    accuracy = 100.0 * correct / total
    return avg_loss, accuracy


# ── Checkpoint ────────────────────────────────────────────────
def save_checkpoint(model, epoch, val_acc, path="checkpoints"):
    os.makedirs(path, exist_ok=True)
    fname = os.path.join(path, f"{{ model }}_epoch{epoch}_acc{val_acc:.2f}.pt")
    torch.save({
        "epoch":      epoch,
        "model":      model.state_dict(),
        "val_acc":    val_acc,
        "config":     CONFIG,
    }, fname)
    log.info(f"Checkpoint saved: {fname}")


# ── Main Training Pipeline ────────────────────────────────────
def main():
    log.info("=" * 60)
    log.info(f"Paper2Code — Training {{ model }} on {{ dataset }}")
    log.info(f"Config: {CONFIG}")
    log.info("=" * 60)

    train_loader, val_loader = get_dataloaders()
    model     = get_model()
    criterion = get_criterion()
    optimizer = get_optimizer(model)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=CONFIG["epochs"])

    best_val_acc = 0.0

    # ── MLflow Experiment Tracking ────────────────────────────
    mlflow.set_experiment("{{ model }}_{{ dataset }}")
    with mlflow.start_run(run_name="paper2code_run"):
        mlflow.log_params(CONFIG)

        for epoch in range(1, CONFIG["epochs"] + 1):
            log.info(f"─── Epoch {epoch}/{CONFIG['epochs']} ───")

            train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, epoch)
            val_loss,   val_acc   = validate(model, val_loader, criterion)
            scheduler.step()

            log.info(
                f"Train → Loss: {train_loss:.4f} | Acc: {train_acc:.2f}%  |  "
                f"Val → Loss: {val_loss:.4f} | Acc: {val_acc:.2f}%"
            )

            # Log to MLflow
            mlflow.log_metrics({
                "train_loss": train_loss, "train_acc": train_acc,
                "val_loss":   val_loss,   "val_acc":   val_acc,
                "lr":         scheduler.get_last_lr()[0],
            }, step=epoch)

            # Save best model
            if val_acc > best_val_acc:
                best_val_acc = val_acc
                save_checkpoint(model, epoch, val_acc)
                mlflow.pytorch.log_model(model, "best_model")
                log.info(f"New best model! Val Acc: {best_val_acc:.2f}%")

        log.info(f"Training complete. Best Val Acc: {best_val_acc:.2f}%")
        mlflow.log_metric("best_val_acc", best_val_acc)


if __name__ == "__main__":
    main()
'''
