"""
app/generator/templates/pytorch_nlp_template.py
PyTorch template for NLP / Language Modeling tasks (GPT, BERT, LSTM, Transformer).
"""

PYTORCH_NLP_TEMPLATE = '''"""
Auto-generated by Paper2Code
Model     : {{ model }}
Dataset   : {{ dataset }}
Task      : {{ task }}
Generated : {{ timestamp }}
"""

import os
import logging
import mlflow
import mlflow.pytorch
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, random_split

# ── Logging Setup ─────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler("training.log"),
    ],
)
log = logging.getLogger("{{ model }}_trainer")

# ── Hyperparameters ───────────────────────────────────────────
CONFIG = {
    "model":       "{{ model }}",
    "dataset":     "{{ dataset }}",
    "epochs":      {{ epochs }},
    "batch_size":  {{ batch_size }},
    "lr":          {{ lr }},
    "optimizer":   "{{ optimizer }}",
    "loss":        "{{ loss }}",
    "vocab_size":  50257,       # GPT-2 default — adjust as needed
    "embed_dim":   256,
    "num_heads":   8,
    "num_layers":  4,
    "seq_len":     128,
    "dropout":     0.1,
    "device":      "cuda" if torch.cuda.is_available() else "cpu",
    "val_split":   0.2,
    "seed":        42,
}

torch.manual_seed(CONFIG["seed"])
device = torch.device(CONFIG["device"])
log.info(f"Using device: {device}")


# ── Dataset ───────────────────────────────────────────────────
class TextDataset(Dataset):
    """
    Simple character/token-level dataset.
    Replace `load_text()` with your actual data source.
    """
    def __init__(self, text, seq_len):
        self.seq_len = seq_len
        # Tokenize at character level — replace with your tokenizer
        chars       = sorted(set(text))
        self.vocab  = {c: i for i, c in enumerate(chars)}
        self.tokens = [self.vocab[c] for c in text]
        CONFIG["vocab_size"] = len(chars)

    def __len__(self):
        return len(self.tokens) - self.seq_len

    def __getitem__(self, idx):
        x = torch.tensor(self.tokens[idx : idx + self.seq_len], dtype=torch.long)
        y = torch.tensor(self.tokens[idx + 1 : idx + self.seq_len + 1], dtype=torch.long)
        return x, y


def load_text() -> str:
    """
    TODO: Replace with your actual dataset.
    Options:
      - Read a .txt file:  return open("data.txt").read()
      - Use HuggingFace:   from datasets import load_dataset
      - WikiText, PTB, etc.
    """
    log.warning("Using dummy text — replace load_text() with your real dataset!")
    return "hello world " * 5000  # placeholder


def get_dataloaders():
    log.info(f"Loading dataset: {CONFIG['dataset']}")
    text    = load_text()
    dataset = TextDataset(text, CONFIG["seq_len"])

    val_size   = int(len(dataset) * CONFIG["val_split"])
    train_size = len(dataset) - val_size
    train_ds, val_ds = random_split(dataset, [train_size, val_size])

    train_loader = DataLoader(train_ds, batch_size=CONFIG["batch_size"],
                              shuffle=True,  num_workers=0)
    val_loader   = DataLoader(val_ds,   batch_size=CONFIG["batch_size"],
                              shuffle=False, num_workers=0)

    log.info(f"Train: {train_size} | Val: {val_size} sequences")
    return train_loader, val_loader


# ── Model ─────────────────────────────────────────────────────
class TransformerModel(nn.Module):
    """
    Decoder-only Transformer — suitable for GPT-style language modeling.
    Modify num_layers, embed_dim, num_heads to match your paper.
    """
    def __init__(self):
        super().__init__()
        self.embedding  = nn.Embedding(CONFIG["vocab_size"], CONFIG["embed_dim"])
        self.pos_embed  = nn.Embedding(CONFIG["seq_len"],    CONFIG["embed_dim"])
        encoder_layer   = nn.TransformerEncoderLayer(
            d_model    = CONFIG["embed_dim"],
            nhead      = CONFIG["num_heads"],
            dim_feedforward = CONFIG["embed_dim"] * 4,
            dropout    = CONFIG["dropout"],
            batch_first= True,
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=CONFIG["num_layers"])
        self.fc_out      = nn.Linear(CONFIG["embed_dim"], CONFIG["vocab_size"])
        self.dropout     = nn.Dropout(CONFIG["dropout"])

    def forward(self, x):
        B, T    = x.shape
        pos     = torch.arange(T, device=x.device).unsqueeze(0)
        x       = self.dropout(self.embedding(x) + self.pos_embed(pos))
        # Causal mask for autoregressive language modeling
        mask    = nn.Transformer.generate_square_subsequent_mask(T, device=x.device)
        x       = self.transformer(x, mask=mask, is_causal=True)
        return self.fc_out(x)


def get_model():
    log.info(f"Building {CONFIG['model']} model")
    model = TransformerModel()
    total_params = sum(p.numel() for p in model.parameters())
    log.info(f"Total parameters: {total_params:,}")
    return model.to(device)


# ── Loss & Optimizer ──────────────────────────────────────────
def get_criterion():
    return nn.CrossEntropyLoss(ignore_index=0)


def get_optimizer(model):
    opts = {
        "Adam":  optim.Adam(model.parameters(),  lr=CONFIG["lr"], betas=(0.9, 0.98)),
        "AdamW": optim.AdamW(model.parameters(), lr=CONFIG["lr"], betas=(0.9, 0.98), weight_decay=0.01),
        "SGD":   optim.SGD(model.parameters(),   lr=CONFIG["lr"]),
    }
    return opts.get(CONFIG["optimizer"], optim.AdamW(model.parameters(), lr=CONFIG["lr"]))


# ── Perplexity ────────────────────────────────────────────────
def compute_perplexity(loss: float) -> float:
    import math
    return math.exp(min(loss, 20))


# ── Training Loop ─────────────────────────────────────────────
def train_one_epoch(model, loader, criterion, optimizer, epoch):
    model.train()
    total_loss, total_tokens = 0.0, 0

    for batch_idx, (inputs, targets) in enumerate(loader):
        try:
            inputs, targets = inputs.to(device), targets.to(device)
            optimizer.zero_grad()
            logits = model(inputs)                          # (B, T, vocab)
            loss   = criterion(
                logits.view(-1, CONFIG["vocab_size"]),
                targets.view(-1)
            )
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)  # gradient clipping
            optimizer.step()
            total_loss   += loss.item() * inputs.size(0)
            total_tokens += inputs.size(0)

            if batch_idx % 100 == 0:
                log.debug(f"Epoch {epoch} | Batch {batch_idx}/{len(loader)} "
                          f"| Loss: {loss.item():.4f} "
                          f"| PPL: {compute_perplexity(loss.item()):.2f}")
        except Exception as e:
            log.error(f"Batch {batch_idx} failed: {e}")
            continue

    avg_loss = total_loss / total_tokens
    return avg_loss, compute_perplexity(avg_loss)


def validate(model, loader, criterion):
    model.eval()
    total_loss, total_tokens = 0.0, 0
    with torch.no_grad():
        for inputs, targets in loader:
            try:
                inputs, targets = inputs.to(device), targets.to(device)
                logits = model(inputs)
                loss   = criterion(logits.view(-1, CONFIG["vocab_size"]), targets.view(-1))
                total_loss   += loss.item() * inputs.size(0)
                total_tokens += inputs.size(0)
            except Exception as e:
                log.error(f"Val batch failed: {e}")
                continue
    avg_loss = total_loss / total_tokens
    return avg_loss, compute_perplexity(avg_loss)


# ── Checkpoint ────────────────────────────────────────────────
def save_checkpoint(model, epoch, val_ppl, path="checkpoints"):
    os.makedirs(path, exist_ok=True)
    fname = os.path.join(path, f"{{ model }}_epoch{epoch}_ppl{val_ppl:.2f}.pt")
    torch.save({"epoch": epoch, "model": model.state_dict(),
                "val_ppl": val_ppl, "config": CONFIG}, fname)
    log.info(f"Checkpoint saved: {fname}")


# ── Main ──────────────────────────────────────────────────────
def main():
    log.info("=" * 60)
    log.info(f"Paper2Code — Training {{ model }} | Task: {{ task }}")
    log.info(f"Config: {CONFIG}")
    log.info("=" * 60)

    train_loader, val_loader = get_dataloaders()
    model     = get_model()
    criterion = get_criterion()
    optimizer = get_optimizer(model)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=CONFIG["epochs"])

    best_val_ppl = float("inf")

    mlflow.set_experiment("{{ model }}_{{ dataset }}")
    with mlflow.start_run(run_name="paper2code_run"):
        mlflow.log_params(CONFIG)

        for epoch in range(1, CONFIG["epochs"] + 1):
            log.info(f"─── Epoch {epoch}/{CONFIG['epochs']} ───")

            train_loss, train_ppl = train_one_epoch(model, train_loader, criterion, optimizer, epoch)
            val_loss,   val_ppl   = validate(model, val_loader, criterion)
            scheduler.step()

            log.info(f"Train → Loss: {train_loss:.4f} | PPL: {train_ppl:.2f}  |  "
                     f"Val → Loss: {val_loss:.4f} | PPL: {val_ppl:.2f}")

            mlflow.log_metrics({
                "train_loss": train_loss, "train_ppl": train_ppl,
                "val_loss":   val_loss,   "val_ppl":   val_ppl,
                "lr":         scheduler.get_last_lr()[0],
            }, step=epoch)

            if val_ppl < best_val_ppl:
                best_val_ppl = val_ppl
                save_checkpoint(model, epoch, val_ppl)
                mlflow.pytorch.log_model(model, "best_model")
                log.info(f"New best model! Val PPL: {best_val_ppl:.2f}")

        log.info(f"Training complete. Best Val Perplexity: {best_val_ppl:.2f}")
        mlflow.log_metric("best_val_ppl", best_val_ppl)


if __name__ == "__main__":
    main()
'''
