"""
app/generator/templates/tensorflow_template.py
Jinja2 template string for TensorFlow/Keras training script generation.
"""

TENSORFLOW_TEMPLATE = '''"""
Auto-generated by Paper2Code
Model     : {{ model }}
Dataset   : {{ dataset }}
Task      : {{ task }}
Generated : {{ timestamp }}
"""

import os
import logging
import mlflow
import mlflow.tensorflow
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, optimizers, losses, callbacks

# ── Logging Setup ─────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler("training.log"),
    ],
)
log = logging.getLogger("{{ model }}_trainer")

# ── Hyperparameters ───────────────────────────────────────────
CONFIG = {
    "model":       "{{ model }}",
    "dataset":     "{{ dataset }}",
    "epochs":      {{ epochs }},
    "batch_size":  {{ batch_size }},
    "lr":          {{ lr }},
    "optimizer":   "{{ optimizer }}",
    "loss":        "{{ loss }}",
    "num_classes": {{ num_classes }},
    "val_split":   0.2,
    "seed":        42,
    "img_size":    (224, 224),
}

tf.random.set_seed(CONFIG["seed"])
np.random.seed(CONFIG["seed"])
log.info(f"TensorFlow version: {tf.__version__}")
log.info(f"GPUs available: {len(tf.config.list_physical_devices('GPU'))}")


# ── Data Pipeline ─────────────────────────────────────────────
def load_data():
    log.info(f"Loading dataset: {CONFIG['dataset']}")
    try:
        (x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()
        x_train = x_train.astype("float32") / 255.0
        x_test  = x_test.astype("float32")  / 255.0
        y_train = keras.utils.to_categorical(y_train, CONFIG["num_classes"])
        y_test  = keras.utils.to_categorical(y_test,  CONFIG["num_classes"])
        log.info(f"Train: {len(x_train)} | Test: {len(x_test)} samples")
        return (x_train, y_train), (x_test, y_test)
    except Exception as e:
        log.error(f"Data loading failed: {e}")
        raise


# ── Model ─────────────────────────────────────────────────────
def build_model():
    log.info(f"Building model: {CONFIG['model']}")
    try:
        {% if model in ["ResNet", "ResNet50"] %}
        base = keras.applications.ResNet50(
            weights="imagenet", include_top=False,
            input_shape=(224, 224, 3)
        )
        base.trainable = False
        {% elif model == "VGG" %}
        base = keras.applications.VGG16(
            weights="imagenet", include_top=False,
            input_shape=(224, 224, 3)
        )
        base.trainable = False
        {% elif model == "EfficientNet" %}
        base = keras.applications.EfficientNetB0(
            weights="imagenet", include_top=False,
            input_shape=(224, 224, 3)
        )
        base.trainable = False
        {% elif model == "MobileNet" %}
        base = keras.applications.MobileNetV2(
            weights="imagenet", include_top=False,
            input_shape=(224, 224, 3)
        )
        base.trainable = False
        {% else %}
        # Custom CNN — modify architecture as needed
        inputs = keras.Input(shape=(32, 32, 3))
        x = layers.Conv2D(64, 3, activation="relu", padding="same")(inputs)
        x = layers.MaxPooling2D()(x)
        x = layers.Conv2D(128, 3, activation="relu", padding="same")(x)
        x = layers.MaxPooling2D()(x)
        x = layers.Conv2D(256, 3, activation="relu", padding="same")(x)
        x = layers.GlobalAveragePooling2D()(x)
        x = layers.Dense(512, activation="relu")(x)
        x = layers.Dropout(0.5)(x)
        outputs = layers.Dense(CONFIG["num_classes"], activation="softmax")(x)
        model = keras.Model(inputs, outputs, name="{{ model }}")
        {% endif %}

        {% if model in ["ResNet", "VGG", "EfficientNet", "MobileNet"] %}
        x = base.output
        x = layers.GlobalAveragePooling2D()(x)
        x = layers.Dense(512, activation="relu")(x)
        x = layers.Dropout(0.5)(x)
        outputs = layers.Dense(CONFIG["num_classes"], activation="softmax")(x)
        model = keras.Model(inputs=base.input, outputs=outputs, name="{{ model }}")
        {% endif %}

    except Exception as e:
        log.error(f"Model build failed: {e}")
        raise

    model.summary()
    return model


# ── Compile ───────────────────────────────────────────────────
def compile_model(model):
    opt_map = {
        "Adam":    optimizers.Adam(learning_rate=CONFIG["lr"]),
        "SGD":     optimizers.SGD(learning_rate=CONFIG["lr"], momentum=0.9),
        "AdamW":   optimizers.AdamW(learning_rate=CONFIG["lr"]),
        "RMSProp": optimizers.RMSprop(learning_rate=CONFIG["lr"]),
    }
    loss_map = {
        "CrossEntropyLoss": "categorical_crossentropy",
        "BCELoss":          "binary_crossentropy",
        "MSELoss":          "mean_squared_error",
    }
    opt  = opt_map.get(CONFIG["optimizer"], optimizers.Adam(learning_rate=CONFIG["lr"]))
    loss = loss_map.get(CONFIG["loss"], "categorical_crossentropy")

    model.compile(optimizer=opt, loss=loss, metrics=["accuracy"])
    log.info(f"Model compiled — Optimizer: {CONFIG['optimizer']} | Loss: {loss}")
    return model


# ── Callbacks ─────────────────────────────────────────────────
def get_callbacks():
    os.makedirs("checkpoints", exist_ok=True)
    return [
        callbacks.ModelCheckpoint(
            "checkpoints/{{ model }}_best.h5",
            monitor="val_accuracy", save_best_only=True, verbose=1
        ),
        callbacks.EarlyStopping(
            monitor="val_loss", patience=5, restore_best_weights=True, verbose=1
        ),
        callbacks.ReduceLROnPlateau(
            monitor="val_loss", factor=0.5, patience=3, verbose=1
        ),
        callbacks.TensorBoard(log_dir="./tensorboard_logs"),
    ]


# ── Main Training Pipeline ────────────────────────────────────
def main():
    log.info("=" * 60)
    log.info(f"Paper2Code — Training {{ model }} on {{ dataset }}")
    log.info(f"Config: {CONFIG}")
    log.info("=" * 60)

    (x_train, y_train), (x_test, y_test) = load_data()
    model = build_model()
    model = compile_model(model)
    cbks  = get_callbacks()

    mlflow.set_experiment("{{ model }}_{{ dataset }}")
    with mlflow.start_run(run_name="paper2code_run"):
        mlflow.log_params(CONFIG)

        log.info("Starting training...")
        history = model.fit(
            x_train, y_train,
            epochs=CONFIG["epochs"],
            batch_size=CONFIG["batch_size"],
            validation_split=CONFIG["val_split"],
            callbacks=cbks,
            verbose=1,
        )

        # Evaluate
        test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)
        log.info(f"Test Loss: {test_loss:.4f} | Test Accuracy: {test_acc*100:.2f}%")

        mlflow.log_metric("test_loss", test_loss)
        mlflow.log_metric("test_accuracy", test_acc)
        mlflow.log_metric("best_val_acc", max(history.history.get("val_accuracy", [0])))
        mlflow.tensorflow.log_model(model, "model")

        log.info("Training complete!")


if __name__ == "__main__":
    main()
'''
